const ERROR_REASON = {
  USER_EXISTS: "USER_EXISTS",
  CREATE_ADMIN_ERROR: "CREATE_ADMIN_ERROR",
  PASSWORD_DOES_NOT_MATCH: "PASSWORD_DOES_NOT_MATCH",
  NAME_OR_DESCRIPTION_OR_MOVIE_DATE_OR_VENUE_MISSING: "NAME_OR_DESCRIPTION_OR_MOVIE_DATE_OR_VENUE_MISSING",
  CREATE_GROUP_ERROR: "CREATE_GROUP_ERROR",
  UPDATE_GROUP_ERROR: "UPDATE_GROUP_ERROR",
  RETRIEVE_GROUP_ERROR: "RETRIEVE_GROUP_ERROR",
  DELETE_GROUP_ERROR: "DELETE_GROUP_ERROR",
  ADD_MEMBERSHIP_ERRROR: "ADD_MEMBERSHIP_ERRROR",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  DELETE_MEMBERSHIP_ERROR: "DELETE_MEMBERSHIP_ERROR",
  USER_OR_GROUP_ID_MISSING: "USER_OR_GROUP_ID_MISSING",
  RETRIEVE_USER_OR_GROUP: "RETRIEVE_USER_OR_GROUP_ERROR",
  RETRIEVE_ADMIN_ERROR: "RETRIEVE_ADMIN_ERROR",
  PREFERRED_MOVIE_ERROR: "PREFERRED_MOVIE_ERROR",
  MOVIE1_OR_MOVIE2_OR_MOVIE3_MISSING: "MOVIE1_OR_MOVIE2_OR_MOVIE3_MISSING",
  MOVIE_SUGGESTION_ERROR: "MOVIE_SUGGESTION_ERROR",
  VOTED_MOVIE_MISSING_ERROR: "VOTED_MOVIE_MISSING_ERROR",
  VOTED_MOVIE_ERROR: "VOTED_MOVIE_ERROR",
  GET_SUGGESTED_MOVIES_ERROR: "GET_SUGGESTED_MOVIES_ERROR",
  ADMIN_CANNOT_DELETE_SELF: "ADMIN_CANNOT_DELETE_SELF",
  GROUP_DOES_NOT_EXIST: "GROUP_DOES_NOT_EXIST",
  ADMIN_DOES_NOT_EXIST: "ADMIN_DOES_NOT_EXIST",
  EMAIL_OR_PASSWORD_MISSING: "EMAIL_OR_PASSWORD_MISSING"
}

module.exports = ERROR_REASON;